# This config contains the settings of the plugin, as well as a list of the names of all rooms, ordered by room type, e.g. the "entry" entryModule.
# These lists enable the plugin to know that room (with schematic and .yml) is there and may be loaded from its respective files.
entryModules:
- entry
- NihonJou
passageWayModules:
- passageWay1
roomModules:
- bridgeTest
- testRoom
- SkeletonBridge
- ThermeErding