name: MineCSweeper
main: mineCSweeper.MCSPlugin
version: 0.1
author: TheRoot89

commands:
   MCS_start:
      description: Starts a new board
      usage: /<command>
   MCS_stop:
      description: Stops the current game and deletes the board. Resets the plugin during Error states.
      usage: /<command>
   MCS_restart: 
      description: Resets the current game
      usage: /<command>
   MCS_set:
      description: Sets a game setting. Possible keys are width, height and nrBombs.
      usage: /<command> <key> <value>