name: MineCSweeper
main: mineCSweeper.MCSPlugin
version: 0.1
author: TheRoot89

commands:
   MCS_start:
      description: Starts a new board or restarts the currently set board.
      usage: /<command>
   MCS_stop:
      description: Stops the current game and deletes the board. Resets the plugin during Error states.
      usage: /<command>
   MCS_set:
      description: Sets a game setting. Possible keys are width, height and nrBombs. Shows current settings if no arguments are given.
      usage: /<command> <key> <value>
   MCS_save:
      description: Saves the current settings to the plugins config file, loaded during startup.
      usage: /<command>
   MCS_add:
      description: Adds more player(s) to the game.
      usage: /<command> <player_name> [player_name] [...]