name: DunGen
main: dunGen.DunGen
version: 0.2
author: TheRoot89

commands:
   stop:
      description: Ends the dungeon and deletes the buildings etc.
      usage: /<command>
   instructions:
      description: Displays the WorldEdit workflow.
      usage: /<command>
   start:
      description: Generates a new dungeon in front of the player.
      usage: /<command>